from typing import Any
from typing import Protocol
from typing import runtime_checkable


@runtime_checkable
class TemporaryStorageService(Protocol):
    def set(self, key: str, value: Any, expiration_seconds: int | None) -> bool: ...
    def get(self, key: str) -> Any: ...
    def delete(self, key: str) -> bool: ...


@runtime_checkable
class UserEncodingService(Protocol):
    def encode(self, phone_number: str) -> str: ...
    def decode(self, token: str) -> str: ...
