from collections.abc import AsyncIterator
from collections.abc import Callable
from typing import Any
from typing import Protocol
from typing import runtime_checkable


@runtime_checkable
class TemporaryStorageService(Protocol):
    def set(self, key: str, value: Any, expiration_seconds: int | None) -> bool: ...
    def get(self, key: str) -> Any: ...
    def delete(self, key: str) -> bool: ...


@runtime_checkable
class UserEncodingService(Protocol):
    def encode(self, phone_number: str) -> str: ...
    def decode(self, token: str) -> str: ...


@runtime_checkable
class AIAgentService(Protocol):
    async def run(self, message_body: str, phone_number: str) -> str: ...


@runtime_checkable
class AMQPService(Protocol):
    async def consume(self, queue_name: str, callback: Callable) -> None: ...
    async def publish(self, message: dict, queue_name: str) -> None: ...


class PubsubService(Protocol):
    async def subscribe(self, channel: str) -> None: ...
    async def publish(self, channel: str, event: str, data: dict) -> None: ...
    async def listen(self) -> AsyncIterator: ...
